### ISSUE TITLE
[REFACTOR] 약속 신청 리팩토링

### ISSUE THREAD

**Issue by loinsir** [TeamSeeMeet/SeeMeet-iOS#69]
## 📌  Feature Issue

약속 신청뷰 리팩토링

## 📝  To-do

- [x] 약속 신청 요청 데이터 싱글턴 패턴 적용
- [x] 약속 신청 하단 시트 뷰 교체

**Comment by yujinnee** [comment]
싱글톤 어느 부분에 적용할 예정인가욤!?!?
하단 시트 뷰는 뭘로 교체 할 예정!?

**Comment by loinsir** [comment]
> 싱글톤 어느 부분에 적용할 예정인가욤!?!? 

약속 신청... 데이터 전달 과정이 너무 많아요... 사용자 입력을 한 객체로 담는게 관리에 용이할것 같습니다.

> 하단 시트 뷰는 뭘로 교체 할 예정!?

구현하지 못했던, 드래그 가능한 시트뷰로 교체해보려고 합니다.🤗
