### ISSUE TITLE
[BUG] UI Target-Action 지정 오류

### ISSUE THREAD

**Issue by loinsir** [TeamSeeMeet/SeeMeet-iOS#85]
## 🐞 버그 설명

addTarget 메서드가 프로퍼티 선언부에 있어서 일부 기기 및 iOS 버전에서 action이 되지 않는 놀라운 상황. 😵‍💫

## 📝 todo
- [ ] addTarget 메서드등 UI이외의 프로퍼티 설정을 선언부에서  분리하여 viewDidLoad에 따로 메서드로 묶어 실행

**Comment by yujinnee** [comment]
프로젝트 모든 부분 다하실건가여?!?
